name = "Advanced AI Command 2"
prefix = "aicommand2"
mainprefix = "z"
author = "Nimmersatt"

[version]
major = 2
minor = 4
patch = 0
build = 0

[files]
include = [
    "LICENSE",
    "logo.paa",
    "mod.cpp"
]
exclude = [
    "*.psd",
    "*.md",
    "*.sh",
    ".*" # dot files
]